# Generated by Django 5.1.2 on 2024-11-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerCheckout', '0005_orderitem_seller_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
