# Generated by Django 5.1.2 on 2024-11-24 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyerStore', '0010_alter_product_price_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerStore.profile')),
            ],
        ),
    ]
