# Generated by Django 5.1.2 on 2024-11-25 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerDashboard', '0002_alter_seller_summary_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_summary',
            name='withdrawals',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='WithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_logs', to='sellerDashboard.seller_summary')),
            ],
        ),
    ]
