# Generated by Django 5.1.2 on 2024-11-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerDashboard', '0003_seller_summary_withdrawals_withdrawallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawallog',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
